/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Connection.ConnectionDatabase;
import config.BCrypt;
import Hotel.Login;
import User.Logout;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rizky
 */
public class AdminPanel extends javax.swing.JFrame {

    // Deklarasi variabel publik untuk menyimpan opsi yang dipilih
    public String adminRole = "";
    public String adminStatus = "";
    
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminMenu = new javax.swing.JPanel();
        reservationButton = new javax.swing.JButton();
        roomManagementButton = new javax.swing.JButton();
        adminProfileButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        bookingListButton = new javax.swing.JButton();
        AdminTabPanel = new javax.swing.JTabbedPane();
        ReservationTab = new javax.swing.JPanel();
        reservationTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchReservationButton = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        cancleBookingButton = new javax.swing.JButton();
        RoomManagementTab = new javax.swing.JPanel();
        roomIDTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomManagementTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchRoomButton = new javax.swing.JButton();
        setAvailableButton = new javax.swing.JButton();
        setUnavailableButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchAdminButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminNameTextField = new javax.swing.JTextPane();
        adminRoleChooser = new javax.swing.JComboBox<>();
        adminStatusChooser = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        insertUpdateAdminButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JPasswordField();
        resetPasswordButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bookingListTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setPreferredSize(new java.awt.Dimension(1100, 400));

        AdminMenu.setBackground(new java.awt.Color(255, 255, 204));

        reservationButton.setText("Reservation");
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        roomManagementButton.setText("Room Management");
        roomManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomManagementButtonActionPerformed(evt);
            }
        });

        adminProfileButton.setText("Admin Profile");
        adminProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminProfileButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        bookingListButton.setText("Booking List");
        bookingListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminMenuLayout = new javax.swing.GroupLayout(AdminMenu);
        AdminMenu.setLayout(AdminMenuLayout);
        AdminMenuLayout.setHorizontalGroup(
            AdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(adminProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AdminMenuLayout.setVerticalGroup(
            AdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(reservationButton)
                .addGap(18, 18, 18)
                .addComponent(roomManagementButton)
                .addGap(18, 18, 18)
                .addComponent(bookingListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(adminProfileButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(60, 60, 60))
        );

        ReservationTab.setPreferredSize(new java.awt.Dimension(1100, 400));

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reservationTable);

        jLabel1.setText("ID Reservation:");

        searchReservationButton.setText("Search");
        searchReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchReservationButtonActionPerformed(evt);
            }
        });

        checkInButton.setText("Check In");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        cancleBookingButton.setText("Cancle Booking");
        cancleBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReservationTabLayout = new javax.swing.GroupLayout(ReservationTab);
        ReservationTab.setLayout(ReservationTabLayout);
        ReservationTabLayout.setHorizontalGroup(
            ReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ReservationTabLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(reservationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchReservationButton)
                        .addGap(217, 217, 217)
                        .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservationTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancleBookingButton)
                .addGap(35, 35, 35))
        );
        ReservationTabLayout.setVerticalGroup(
            ReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ReservationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(searchReservationButton)
                    .addComponent(checkInButton)
                    .addComponent(checkOutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancleBookingButton)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        AdminTabPanel.addTab("Reservation", ReservationTab);

        roomManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(roomManagementTable);

        jLabel2.setText("ID Room:");

        searchRoomButton.setText("Search");
        searchRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRoomButtonActionPerformed(evt);
            }
        });

        setAvailableButton.setText("Set Available");
        setAvailableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAvailableButtonActionPerformed(evt);
            }
        });

        setUnavailableButton.setText("Set Unavailable");
        setUnavailableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUnavailableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomManagementTabLayout = new javax.swing.GroupLayout(RoomManagementTab);
        RoomManagementTab.setLayout(RoomManagementTabLayout);
        RoomManagementTabLayout.setHorizontalGroup(
            RoomManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomManagementTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(RoomManagementTabLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchRoomButton)
                        .addGap(35, 35, 35)
                        .addComponent(setAvailableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setUnavailableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RoomManagementTabLayout.setVerticalGroup(
            RoomManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomManagementTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(RoomManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(searchRoomButton)
                    .addComponent(setAvailableButton)
                    .addComponent(setUnavailableButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        AdminTabPanel.addTab("Room Management", RoomManagementTab);

        jLabel3.setText("Admin Name:");

        jLabel4.setText("Admin Role:");

        jLabel5.setText("Admin Status:");

        searchAdminButton.setText("Search");
        searchAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdminButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(adminNameTextField);

        adminRoleChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super", "Management", "Receptionist" }));
        adminRoleChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRoleChooserActionPerformed(evt);
            }
        });

        adminStatusChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Suspend" }));
        adminStatusChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStatusChooserActionPerformed(evt);
            }
        });

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(adminTable);

        insertUpdateAdminButton.setText("Insert/Update");
        insertUpdateAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertUpdateAdminButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Admin Password:");

        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(adminRoleChooser, 0, 200, Short.MAX_VALUE)
                            .addComponent(adminStatusChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(insertUpdateAdminButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetPasswordButton)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchAdminButton)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adminRoleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStatusChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(insertUpdateAdminButton)
                    .addComponent(resetPasswordButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        AdminTabPanel.addTab("Admin", jPanel1);

        bookingListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(bookingListTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        AdminTabPanel.addTab("Booking List", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(AdminTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchReservationButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database

        try {
            // Query untuk mengambil informasi kamar
            String query = "SELECT * FROM reservation r JOIN user u ON r.userid = u.userid WHERE reservation_id = ?";

            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, reservationTextField.getText());

            // Eksekusi kueri
            ResultSet rs = statement.executeQuery();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Room Number");
            model.addColumn("Check In");
            model.addColumn("Check Out");
            model.addColumn("Bills");
            model.addColumn("Status");
            model.addColumn("Reservation Notes");
            model.addColumn("Full Name"); // Kolom tambahan untuk tombol Select


            // Memproses hasil query untuk menambahkan baris ke dalam model tabel
            while (rs.next()) {
                String roomId = rs.getString("room_id");
                String checkIn = rs.getString("check_in");
                String checkOut = rs.getString("check_out");
                String Bills = rs.getString("reservation_bills");
                String billsStatus = rs.getString("bill_status");
                String notes = rs.getString("reservation_notes");
                String FullName = rs.getString("fullname");

                // Tambahkan baris ke dalam model tabel
                model.addRow(new Object[]{roomId, checkIn, checkOut, Bills, billsStatus, notes, FullName});
            }

            // Set model tabel
            reservationTable.setModel(model);

            // Tutup statement dan result set
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Memuat Kamar", "Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            // Menutup koneksi setelah selesai digunakan
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                // Tangani kesalahan penutupan koneksi
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchReservationButtonActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        // TODO add your handling code here:
        String cekInID = reservationTextField.getText();
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        // Mendapatkan tanggal hari ini
        java.util.Date today = new java.util.Date();
        try {
            // Query untuk check In
            String query = "UPDATE reservation SET bill_status = ?, reservation_notes = ? WHERE reservation_id = ? AND reservation_status = ?";
            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, "Paid via Cash");
            statement.setString(2, "Check In: " + today);
            statement.setString(3, cekInID); // Mengatur nilai untuk parameter kedua (reservation_id)
            statement.setString(4, "Booked");

            // Eksekusi kueri
            int rowsUpdated = statement.executeUpdate(); // Menggunakan executeUpdate() untuk menjalankan query UPDATE
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Check In Pada: " + today, "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Mengupdate Check In", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Mengupdate Check In", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        String cekOutID = reservationTextField.getText();
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        // Mendapatkan tanggal hari ini
        java.util.Date today = new java.util.Date();
        String CheckOut = reservationNotes(conn, cekOutID);
        try {
            // Query untuk check In
            String query = "UPDATE reservation SET reservation_status = ?, reservation_notes = ? WHERE reservation_id = ? AND bill_status = ?";
            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, "Check Out");
            statement.setString(2, CheckOut + " AND Check Out: " + today);
            statement.setString(3, cekOutID); // Mengatur nilai untuk parameter kedua (reservation_id)
            statement.setString(4, "Paid via Cash");

            // Eksekusi kueri
            int rowsUpdated = statement.executeUpdate(); // Menggunakan executeUpdate() untuk menjalankan query UPDATE
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Check Out Pada: " + today, "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Mengupdate Check Out", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Mengupdate Check Out", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private String reservationNotes(Connection conn, String ID){
        String checkOutNotes = "";
        try {
            // Query untuk check Out
            String query = "SELECT reservation_notes FROM reservation WHERE reservation_id = ?";
            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, ID);

            // Eksekusi kueri
            ResultSet rs = statement.executeQuery();

            // Periksa apakah ResultSet mengandung baris
            if (rs.next()) {
                checkOutNotes = rs.getString("reservation_notes");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Mengecek Check Out", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return checkOutNotes;
    }
    
    private void adminProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminProfileButtonActionPerformed
        // TODO add your handling code here:
        AdminTabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_adminProfileButtonActionPerformed

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
        AdminTabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void roomManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomManagementButtonActionPerformed
        // TODO add your handling code here:
        AdminTabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_roomManagementButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new Logout().removeUser();
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdminButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database

        try {
            // Query untuk mengambil informasi kamar
            String query = "SELECT * FROM admin WHERE adminName = ?";

            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, adminNameTextField.getText());

            // Eksekusi kueri
            ResultSet rs = statement.executeQuery();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Admin ID");
            model.addColumn("Admin Name");
            model.addColumn("Admin Role");
            model.addColumn("Admin Status");


            // Memproses hasil query untuk menambahkan baris ke dalam model tabel
            while (rs.next()) {
                String adminId = rs.getString("adminid");
                String adminName = rs.getString("adminName");
                String adminRoles = rs.getString("adminRole");
                String adminStats = rs.getString("adminStatus");

                // Tambahkan baris ke dalam model tabel
                model.addRow(new Object[]{adminId, adminName, adminRoles, adminStats});
            }

            // Set model tabel
            adminTable.setModel(model);

            // Tutup statement dan result set
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Memuat Kamar", "Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            // Menutup koneksi setelah selesai digunakan
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                // Tangani kesalahan penutupan koneksi
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchAdminButtonActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        
        String adminPass = new String (adminPasswordField.getPassword());
        String Pass = hashPassword(adminPass);
        
        try {
            // Query untuk check In
            String query = "UPDATE admin SET adminPass = ? WHERE adminName = ?";
            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, Pass);
            statement.setString(2, adminNameTextField.getText());

            // Eksekusi kueri
            int rowsUpdated = statement.executeUpdate(); // Menggunakan executeUpdate() untuk menjalankan query UPDATE
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Reset Password", "Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Reset Password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Mengupdate Password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void bookingListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingListButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database

        try {
            // Query untuk mengambil informasi kamar
            String query = "SELECT * FROM reservation r JOIN user u ON r.userid = u.userid WHERE reservation_status = ?";

            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, "Booked");

            // Eksekusi kueri
            ResultSet rs = statement.executeQuery();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Room");
            model.addColumn("Full Name");
            model.addColumn("Check In");
            model.addColumn("Check Out");
            model.addColumn("Total Nights");
            model.addColumn("Bills");
            model.addColumn("Bills Status");
            model.addColumn("Book Status");


            // Memproses hasil query untuk menambahkan baris ke dalam model tabel
            while (rs.next()) {
                String reserID = rs.getString("reservation_id");
                String roomNum = rs.getString("room_id");
                String fullname = rs.getString("fullname");
                String ckIn = rs.getString("check_in");
                String ckOut = rs.getString("check_out");
                String tNights = rs.getString("totalNights");
                String bills = rs.getString("reservation_bills");
                String payStatus = rs.getString("bill_status");
                String status = rs.getString("reservation_status");
                
                // Tambahkan baris ke dalam model tabel
                model.addRow(new Object[]{reserID, roomNum, fullname, ckIn, ckOut, tNights, bills, payStatus, status});
            }

            // Set model tabel
            bookingListTable.setModel(model);

            // Tutup statement dan result set
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Memuat Kamar", "Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            // Menutup koneksi setelah selesai digunakan
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                // Tangani kesalahan penutupan koneksi
                e.printStackTrace();
            }
        }
        
        AdminTabPanel.setSelectedIndex(3);
    }//GEN-LAST:event_bookingListButtonActionPerformed

    private void cancleBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBookingButtonActionPerformed
        // TODO add your handling code here:
        String ID = reservationTextField.getText();
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        // Mendapatkan tanggal hari ini
        java.util.Date today = new java.util.Date();
        String Notes = reservationNotes(conn, ID);
        
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin membatalkan reservasi ini?", "Konfirmasi Pembatalan", JOptionPane.YES_NO_OPTION);
    
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Query untuk check In
                String query = "UPDATE reservation SET reservation_status = ?, reservation_notes = ? WHERE reservation_id = ?";
                // Persiapkan statement
                PreparedStatement statement = conn.prepareStatement(query);
                statement.setString(1, "Canceled");
                statement.setString(2, Notes + " AND Canceled on: " + today);
                statement.setString(3, ID); // Mengatur nilai untuk parameter ketiga (reservation_id)

                // Eksekusi kueri
                int rowsUpdated = statement.executeUpdate(); // Menggunakan executeUpdate() untuk menjalankan query UPDATE
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Reservasi berhasil dibatalkan pada:  " + today, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal membatalkan reservasi", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                // Tangani pengecualian sesuai kebutuhan Anda
                JOptionPane.showMessageDialog(null, "Gagal membatalkan reservasi", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cancleBookingButtonActionPerformed

    private void insertUpdateAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertUpdateAdminButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        
        String adminName = adminNameTextField.getText();
        String adminPass = new String(adminPasswordField.getPassword());
        String Pass = hashPassword(adminPass);
        try {
            // Mengecek apakah admin dengan nama yang sama sudah ada dalam tabel
            PreparedStatement checkStatement = conn.prepareStatement("SELECT COUNT(*) FROM admin WHERE adminName = ?");
            checkStatement.setString(1, adminName);
            ResultSet rs = checkStatement.executeQuery();
            rs.next();
            int count = rs.getInt(1);

            if (count > 0) {
                // Jika admin dengan nama yang sama sudah ada, lakukan update
                PreparedStatement updateStatement = conn.prepareStatement("UPDATE admin SET adminRole = ?, adminStatus = ? WHERE adminName = ?");
                updateStatement.setString(1, adminRole);
                updateStatement.setString(2, adminStatus);
                updateStatement.setString(3, adminName);
                updateStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data admin diupdate.");
            } else {
                // Jika tidak ada admin dengan nama yang sama, lakukan insert
                PreparedStatement insertStatement = conn.prepareStatement("INSERT INTO admin (adminName, adminPass, adminRole, adminStatus) VALUES (?, ?, ?, ?)");
                insertStatement.setString(1, adminName);
                insertStatement.setString(2, Pass);
                insertStatement.setString(3, adminRole);
                insertStatement.setString(4, adminStatus);
                insertStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data admin ditambahkan.");
            }

            // Tutup statement dan koneksi
            rs.close();
            conn.close();
        } catch (SQLException ex) {
            // Tangani kesalahan SQL
            ex.printStackTrace();
        }
    }//GEN-LAST:event_insertUpdateAdminButtonActionPerformed

    private void searchRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRoomButtonActionPerformed
        // TODO add your handling code here:
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        String roomid = roomIDTextField.getText();
        try {
            // Query untuk mengambil informasi kamar
            String query = "SELECT * FROM room WHERE room_id = ?";

            // Persiapkan statement
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, roomid);

            // Eksekusi kueri
            ResultSet rs = statement.executeQuery();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Room Number");
            model.addColumn("Room Name");
            model.addColumn("Room Bed");
            model.addColumn("Room Capacity");
            model.addColumn("Room Floor");
            model.addColumn("Room Type");
            model.addColumn("Room Price");
            model.addColumn("Room Status");
            
            // Memproses hasil query untuk menambahkan baris ke dalam model tabel
            while (rs.next()) {
                String id = rs.getString("room_id");
                String roomname = rs.getString("room_name");
                String roombed = rs.getString("room_bed");
                String roomcap = rs.getString("room_capacity");
                String roomfloor = rs.getString("room_floor");
                String roomtype = rs.getString("room_type");
                String rprice = rs.getString("room_price");
                String rstatus = rs.getString("room_status");
                
                // Tambahkan baris ke dalam model tabel
                model.addRow(new Object[]{id, roomname, roombed, roomcap, roomfloor, roomtype, rprice, rstatus});
            }

            // Set model tabel
            roomManagementTable.setModel(model);

            // Tutup statement dan result set
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Tangani pengecualian sesuai kebutuhan Anda
            JOptionPane.showMessageDialog(null, "Gagal Memuat Kamar", "Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            // Menutup koneksi setelah selesai digunakan
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                // Tangani kesalahan penutupan koneksi
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchRoomButtonActionPerformed

    private void adminRoleChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRoleChooserActionPerformed
        // TODO add your handling code here:
        // Mendapatkan opsi yang dipilih
        adminRole = (String) adminRoleChooser.getSelectedItem();
    }//GEN-LAST:event_adminRoleChooserActionPerformed

    private void adminStatusChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStatusChooserActionPerformed
        // TODO add your handling code here:
        // Mendapatkan opsi yang dipilih
        adminStatus = (String) adminStatusChooser.getSelectedItem();
    }//GEN-LAST:event_adminStatusChooserActionPerformed

    private void setAvailableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAvailableButtonActionPerformed
        // TODO add your handling code here:
        String roomid = roomIDTextField.getText();
        String status = "Available";
        updateRoom(status, roomid);
    }//GEN-LAST:event_setAvailableButtonActionPerformed

    private void setUnavailableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUnavailableButtonActionPerformed
        // TODO add your handling code here:
        String roomid = roomIDTextField.getText();
        String status = "Unavailable";
        updateRoom(status, roomid);
    }//GEN-LAST:event_setUnavailableButtonActionPerformed

    private void updateRoom(String Status, String roomid){
        // Connect into database and fetching user data
        ConnectionDatabase database = new ConnectionDatabase();
        Connection conn = database.connect(); // Memanggil metode connect untuk membuat koneksi ke database
        
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengubah Status Kamar?", "Konfirmasi Pengubahan", JOptionPane.YES_NO_OPTION);
    
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Query untuk check In
                String query = "UPDATE room SET room_status = ? WHERE room_id = ?";
                // Persiapkan statement
                PreparedStatement statement = conn.prepareStatement(query);
                statement.setString(1, Status);
                statement.setString(2, roomid);

                // Eksekusi kueri
                int rowsUpdated = statement.executeUpdate(); // Menggunakan executeUpdate() untuk menjalankan query UPDATE
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Room Number: " + roomid + " Berhasil Diubah Menjadi " + Status, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal mengubah status kamar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                // Tangani pengecualian sesuai kebutuhan Anda
                JOptionPane.showMessageDialog(null, "Gagal mengubah status kamar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    // Metode untuk menghash password menggunakan BCrypt
    private String hashPassword(String password) {
        return BCrypt.hashpw(password, BCrypt.gensalt());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminMenu;
    private javax.swing.JTabbedPane AdminTabPanel;
    private javax.swing.JPanel ReservationTab;
    private javax.swing.JPanel RoomManagementTab;
    private javax.swing.JTextPane adminNameTextField;
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JButton adminProfileButton;
    private javax.swing.JComboBox<String> adminRoleChooser;
    private javax.swing.JComboBox<String> adminStatusChooser;
    private javax.swing.JTable adminTable;
    private javax.swing.JButton bookingListButton;
    private javax.swing.JTable bookingListTable;
    private javax.swing.JButton cancleBookingButton;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton insertUpdateAdminButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton reservationButton;
    private javax.swing.JTable reservationTable;
    private javax.swing.JTextField reservationTextField;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JTextField roomIDTextField;
    private javax.swing.JButton roomManagementButton;
    private javax.swing.JTable roomManagementTable;
    private javax.swing.JButton searchAdminButton;
    private javax.swing.JButton searchReservationButton;
    private javax.swing.JButton searchRoomButton;
    private javax.swing.JButton setAvailableButton;
    private javax.swing.JButton setUnavailableButton;
    // End of variables declaration//GEN-END:variables
}
